### ISSUE TITLE
Karpenter support

### ISSUE THREAD

**Issue by FalconerTC** [grafana/kubectl-nodepools#3]
Maybe this is out of scope for this, but support for Karpenter managed node pools would be a nice feature I think

**Comment by inkel** [comment]
Hi! Thanks for creating this issue. I honestly never heard of Karpenter, I assume you're talking about [this project](https://karpenter.sh/), correct? I'm reading the docs and I couldn't find a reference to node pools there, only [node templates](https://karpenter.sh/v0.23.0/concepts/node-templates/) which seem to be something similar, but I'm failing to see if the nodes get created with any specific label that could help with this. I'll continue to investigate, though, but if you know the answer I'm more than happy to try and add it, or even review a PR :wink:

**Comment by logyball** [comment]
Closed by #7

**Comment by inkel** [comment]
Re-opening now that Karpenter has introduced [nodepools](https://karpenter.sh/docs/concepts/nodepools/). This will probably need some refactoring of #7 too.

**Comment by logyball** [comment]
Looks like the only real upgrade will be changing the label from `karpenter.sh/provisioner-name` to `karpenter.sh/nodepool`, but we may want to consider if we'll support both the `v1alpha5` spec of the Karpenter API, or go with just a clean break and do the `v1beta1` API

**Comment by inkel** [comment]
@logyball with the changes in #11, will this one consider close now?

**Comment by logyball** [comment]
I'd say so! Closing
