### ISSUE TITLE
Allow a custom node group label 

### ISSUE THREAD

**Issue by tavisto** [grafana/kubectl-nodepools#5]
In order to use this with other types of clusters, or cloud clusters that have a custom label defined. There should be a flag that you can pass a custom label to the command for grouping nodes into pools.

**Comment by inkel** [comment]
I **LOVE** this idea! Let me review your PR, thanks!

**Comment by inkel** [comment]
Version v0.0.3 of the plugin has just been released, which includes your changes. Thank you again!
